### ISSUE TITLE
RBC50D1S-G1 renogy charger supported?

### ISSUE THREAD

**Issue by riker65** [enwi/RNGToWiFi#1]
Hi Moritz,

could you check support of this product? Not in your list yet.

RS485

[DCC50S](https://www.renogy.com/dcc50s-12v-50a-dc-dc-on-board-battery-charger-with-mppt/)

Thanks T

**Comment by enwi** [comment]
@riker65
The DCC50S is not supported. Mainly due to RS485 being incompatible with RS232 and `RNGToWiFi` only supports RS232.
![](https://www.virtual-serial-port.org/images/upload/products/vspd/articles/difference/1.jpg)
Though I could possibly make a version that works with RS485 and RS422
